Aplicações/Sistema juridico/Code/src/java/View/ManageLoginManagedBean.java
package View;


import Utilitarios.EmProvider;
import Controler.exceptions.IllegalOrphanException;
import Controler.exceptions.NonexistentEntityException;
import Components.ComponentsContainer;
import Controler.AdminJpaController;
import Model.Admin;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;


public class ManageLoginManagedBean {
    
    
    public ManageLoginManagedBean() {
    }
    
    private Admin actualAdmin = new Admin();
    private List<Admin> administrator = new ArrayList<>();
    private AdminJpaController control = new AdminJpaController(EmProvider.getInstance().getEntityManagerFactory());
    
    
    public String gotoLogin(){
        return "/Admin/login";
    }
     
      
      
    public String finishEditarAdministrador() throws NonexistentEntityException, Exception, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException{
        control.edit(actualAdmin);
        actualAdmin = new Admin();
        return "gotoGerenciarAdministrador";
    }
   
     
    public String gotoGerenciarAdministrador(){ 
        //SecretariaJpaController control = new SecretariaJpaController(EmProvider.getInstance().getEntityManagerFactory());
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String gotoAdicionarAdministrador(){
        return "gotoAdicionarAdministrador";
    }
    
    public String finishAdicionarAdministrador() throws Exception{
        control.create(actualAdmin);
        actualAdmin = new Admin();
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String excluirAdministrador() throws IllegalOrphanException, NonexistentEntityException{
        //PrefeitoJpaController control = new PrefeitoJpaController(EmProvider.getInstance().getEntityManagerFactory());
        control.destroy(actualAdmin.getLoginUser());
        actualAdmin = new Admin();
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String gotoAdicionarArquivoAdministrador(){
        actualAdmin = control.findAdmin(actualAdmin.getLoginUser());
        return "gotoAdicionarArquivoAdministrador";
    }
    
    public String gotoVisualizarImagem(){
        return "gotoVisualizarImagem";
    }
    
    public String finalizarAdicaoFotosAdministrador(){
        return "gotoGerenciarAdministrador";
    }
    
    public String validateUsernamePassword() {
        
        
        if (validateUser(actualAdmin)) {
            HttpSession session = ManageSession.getSession();
            session.setAttribute("username", actualAdmin.getLoginUser());
            return "Welcome";
        } else {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                            "Senha Incorreta",
                            "Por favor, tente novamente"));
            return "login";
        }
    }
    
    public boolean validateUser(Admin comparar){
        Admin validate = control.findAdmin(actualAdmin.getLoginUser());
        if (validate == null){
            return false;
        }
        if(validate.getLoginUser().equals(comparar.getLoginUser()) && 
                validate.getPasswordUser().equals(comparar.getPasswordUser())){
            return true;
        }
        return false;
    }
 
    //logout event, invalidate session
    public String logout() {
        HttpSession session = ManageSession.getSession();
        session.invalidate();
        return "/Public/Dashboard";
    }
    
    public ComponentsContainer getComponentsContainer(){
        return new ComponentsContainer();
    }
    
    public Admin getActualAdmin() {
        return actualAdmin;
    }

    public void setActualAdmin(Admin actualAdmin) {
        this.actualAdmin = actualAdmin;
    }

    public List<Admin> getAdmin() {
        return administrator;
    }

    public void setAdmin(List<Admin> administrator) {
        this.administrator = administrator;
    }

    public AdminJpaController getControl() {
        return control;
    }

    public void setControl(AdminJpaController control) {
        this.control = control;
    }

    
    
    
    
}

Aplicações/Sistema juridico/Code/src/java/View/ManageTagsManagedBean.java
package View;

import Controler.TagJpaController;
import Controler.AdminJpaController;
import Controler.exceptions.NonexistentEntityException;
import Model.Tag;
import Utilitarios.EmProvider;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

@ManagedBean
@RequestScoped
public class ManageTagsManagedBean {

    //Tags
    private Tag actualTag = new Tag();
    private Tag selectedTag = new Tag();

    //lists
    private List<Tag> listTags = new ArrayList<>();

    //controllers
    private TagJpaController controlTags = new TagJpaController(EmProvider.getInstance().getEntityManagerFactory());
    private AdminJpaController controlUser = new AdminJpaController(EmProvider.getInstance().getEntityManagerFactory());

    //Auxiliarys
    private String tagTypeOfInsertion;
    private String filter;
    private TreeNode TagsTree;

    public ManageTagsManagedBean() {
    }

    public void loadTree() {
        TagsTree = new DefaultTreeNode();
        Tag root = controlTags.findTag(1); // instead get root object from database 
        TagsTree = newNodeWithChildren(root, null);
    }

    public TreeNode newNodeWithChildren(Tag ttParent, TreeNode parent) {
        TreeNode newNode = new DefaultTreeNode(ttParent, parent);
        for (Tag tt : ttParent.getTagList()) {
            TreeNode newNode2 = newNodeWithChildren(tt, newNode);
        }
        return newNode;
    }

    //goto
    public boolean isNewClassificationSelected() {
        if (tagTypeOfInsertion == null) {
            return false;
        } else if (tagTypeOfInsertion.equals("newClassification")) {
            return true;
        }
        return false;
    }

    public boolean isEditClassificationSelected() {
        if (tagTypeOfInsertion == null) {
            return false;
        } else if (tagTypeOfInsertion.equals("editClassification")) {
            return true;
        }
        return false;
    }

    public boolean isRemoveClassificationSelected() {
        if (tagTypeOfInsertion == null) {
            return false;
        } else if (tagTypeOfInsertion.equals("removeClassification")) {
            return true;
        }
        return false;
    }

    public void finishAddTag() {
        try {

            if (selectedTag == null || selectedTag.getTitle() == null) {
                actualTag.setLevel(1);
                actualTag.setParentId(controlTags.findTag(1));
                controlTags.create(actualTag);
            } else {
                actualTag.setParentId(selectedTag);
                controlTags.create(actualTag);
            }
            loadTree();
            actualTag = new Tag();
        } catch (Exception ex) {
            Logger.getLogger(ManageTagsManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // edit
    public void finishEditTag() {
        try {
            List<Tag> results = EmProvider.getInstance().getEntityManagerFactory().createEntityManager().createNamedQuery("Tag.findByTitle")
                    .setParameter("title", selectedTag.getTitle())
                    .getResultList();
            Tag toPersist = results.get(0);
            toPersist.setTitle(actualTag.getTitle());

            controlTags.edit(toPersist);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ManageTagsManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha :("));
        } catch (Exception ex) {
            Logger.getLogger(ManageTagsManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha!"));
        }
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Sucesso!"));
        selectedTag = new Tag();
        actualTag = new Tag();
        loadTree();
    }

    // edit
    //Excluir
    public void removeTag() {
        try {
            controlTags.destroy(selectedTag.getIdTag());
            actualTag = new Tag();
            loadTree();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void unselectTag() {
        selectedTag = null;
    }

    public Tag getActualTag() {
        return actualTag;
    }

    public void setActualTag(Tag actualTag) {
        this.actualTag = actualTag;
    }

    public Tag getSelectedTag() {
        return selectedTag;
    }

    public void setSelectedTag(Tag selectedTag) {
        this.selectedTag = selectedTag;
    }

    public List<Tag> getListTags() {
        return listTags;
    }

    public void setListTags(List<Tag> listTags) {
        this.listTags = listTags;
    }

    public String getTagTypeOfInsertion() {
        return tagTypeOfInsertion;
    }

    public void setTagTypeOfInsertion(String tagTypeOfInsertion) {
        this.tagTypeOfInsertion = tagTypeOfInsertion;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    public TreeNode getTagsTree() {
        return TagsTree;
    }

    public void setTagsTree(TreeNode TagsTree) {
        this.TagsTree = TagsTree;
    }

}

Aplicações/Sistema juridico/Code/web/Public/DocumentsModule/ManageDocuments.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p ="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:fn="http://java.sun.com/jsp/jstl/core">



    <ui:include src="/Public/Includes/HeadIncludesPublic.xhtml"/>

    <f:metadata>
        <f:viewAction action="#{ManageDocumentsManagedBean.loadTree()}"/>
    </f:metadata>


    <h:body>

        <div class="content">
            <ui:include src="/Public/Components/Headers/Header.xhtml"/>

            <fn:choose>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.primeNav}">
                    <ui:include src="/Public/Components/Navs/PrimeNav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.defaultNav}">
                    <ui:include src="/Public/Components/Navs/Nav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.bootstrapNav}">
                    <ui:include src="/Public/Components/Navs/BootstrapNav.xhtml"/>
                </fn:when>

            </fn:choose>

            <h:form>
                <nav class="positionSideLinks tree">
                    <p:commandButton class="colorLink" action="#{ManageDocumentsManagedBean.goToAddDocuments}" value="Criar novo documento"/>
                    <div class="tituloTopico centralizar" style="margin-top: ">Classificações</div>

                    <p:tree style="width:100%; float:right" dynamic="true" cache="false" value="#{ManageDocumentsManagedBean.root}" var="node">
                        <p:treeNode>
                            <p:commandLink update="@form" action="#{ManageDocumentsManagedBean.filterDocumentsByTag()}" value="#{node}" >
                                <f:setPropertyActionListener target="#{ManageDocumentsManagedBean.selectedTag}" value="#{node}"/>
                            </p:commandLink>
                        </p:treeNode>
                    </p:tree>

                    <div class="boardManipulateTag">




                    </div>
                </nav>
                <div class="page-content">

                    <div class="tituloTopico">jusHelp - Gerencie seus documentos</div>

                    <div class="textoExtenso">
                        Gerencie nesta página todos os seus modelos inseridos no sistema. Os modelos são bases para os documentos que você
                        irá gerar posteriormente. 

                    </div>

                    <div class="formElements" style="margin-left: 0">
                         <p:inputText value="#{ManageDocumentsManagedBean.filterDocumentName}" class="centralizar" placeholder="Digite nome do arquivo e clique em buscar">
                            <p:ajax event="keyup" listener="#{ManageDocumentsManagedBean.filterDocumentsByName}" update="tableDocuments"/>
                        </p:inputText>
                    </div>

                    <div class="tablePannel" style="float: left; margin-top: 3%">
                        <p:dataTable id="tableDocuments" var="cli"  paginator="true" rows="10" value="#{ManageDocumentsManagedBean.listDocuments}">

                            <p:column headerText="Nome completo">
                                <h:outputText value="#{cli.title}" />
                            </p:column>

                            <p:column headerText="Summary">
                                <h:outputText value="#{cli.summary}" />
                            </p:column>

                            <p:column headerText="Classificação">
                                <h:outputText value="#{cli.tagidTag.title}" />
                            </p:column>

                            <p:column style="width: 23%" headerText="Actions">
                                <p:commandButton icon="ui-icon-search" action="#{ManageDocumentsManagedBean.goToVisualizeDocument}" update="@form" >
                                    <f:setPropertyActionListener target="#{ManageDocumentsManagedBean.actualDocument}" value="#{cli}"/>
                                </p:commandButton>
                                <p:commandButton icon="ui-icon-close" action="#{ManageDocumentsManagedBean.removeDocument()}" update="@form" >
                                    <f:setPropertyActionListener target="#{ManageDocumentsManagedBean.actualDocument}" value="#{cli}"/>
                                    <p:confirm header="Confirmação" message="tem certeza que deseja excluir este documento??" icon="ui-icon-alert" />
                                </p:commandButton>

                                <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                    <p:commandButton value="Sim" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                                    <p:commandButton value="Não" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                                </p:confirmDialog>

                                <p:commandButton icon="ui-icon-pencil" action="#{ManageDocumentsManagedBean.goToEditDocument()}">
                                    <f:setPropertyActionListener target="#{ManageDocumentsManagedBean.actualDocument}" value="#{cli}"/>
                                </p:commandButton>

                            </p:column>
                        </p:dataTable>
                    </div>   



                </div>
            </h:form>
        </div>


        <fn:choose>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.defaultFooter}">
                <ui:include src="/Public/Components/Footers/DefaultFooter.xhtml"/>
            </fn:when>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.slimFooter}">
                <ui:include src="/Public/Components/Footers/SlimFooter.xhtml"/>
            </fn:when>
        </fn:choose>
    </h:body>
</html>

Aplicações/Sistema juridico/Code/web/Public/DocumentsModule/VisualizeDocument.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p ="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:fn="http://java.sun.com/jsp/jstl/core"
      xmlns:pe="http://primefaces.org/ui/extensions">


    <f:metadata>
        <f:viewAction action="#{ManageModelsManagedBean.loadTree()}"/>
    </f:metadata>

    <ui:include src="/Public/Includes/HeadIncludesPublic.xhtml"/>


    <h:body>

        <div class="content">
            <ui:include src="/Public/Components/Headers/Header.xhtml"/>

            <fn:choose>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.primeNav}">
                    <ui:include src="/Public/Components/Navs/PrimeNav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.defaultNav}">
                    <ui:include src="/Public/Components/Navs/Nav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.bootstrapNav}">
                    <ui:include src="/Public/Components/Navs/BootstrapNav.xhtml"/>
                </fn:when>

            </fn:choose>


            <div class="page-content">



                <div class="tituloTopico">jusHelp - Visualizador de documentos</div>



                <div class="textoExtenso">Utilize esta interface para visualizar o documento e exporta-lo para pdf.</div>
                <h:form>

                    <div class="formElements">
                        <div>Título: #{ManageDocumentsManagedBean.actualDocument.title}</div>
                        <div>Resumo: #{ManageDocumentsManagedBean.actualDocument.summary}</div>
                        <div>Classificação #{ManageDocumentsManagedBean.actualDocument.tagidTag.title}</div>

                    </div>

                    <p:commandButton style="margin-top: 5%" class="colorLink centralizar" icon="ui-icon-pencil" value=" Clique aqui para editar este documento" action="#{ManageDocumentsManagedBean.goToEditDocument()}"/>

                    <div class="centralizar" style="margin-top: 5%">
                        <pe:ckEditor readonly="true" value="#{ManageDocumentsManagedBean.actualDocument.corpus}" height="900" width="100%"/>
                    </div>

                    <p:commandButton class="centralizar colorLink" value="Voltar" action="#{ManageDocumentsManagedBean.goToManageDocuments()}"/>


                </h:form>


            </div>

            <div class="positionSideLinks tree">
                <div class="tituloTopico" style="margin-top: ">Classificações</div>
                <div></div>
                <h:form>

                    <p:tree style="width:100%; float:right" dynamic="true" cache="false" value="#{ManageModelsManagedBean.root}" var="node">
                        <p:treeNode>
                            <p:commandLink update="@form" value="#{node}" >
                                <f:setPropertyActionListener target="#{ManageModelsManagedBean.selectedTag}" value="#{node}"/>
                            </p:commandLink>
                        </p:treeNode>
                    </p:tree>

                    <div class="boardManipulateTag">


                        <div class="tituloTopico centralizar">Opções</div>

                        <h:outputText value="Selecione uma ação" />
                        <h:panelGrid columns="1" style="margin-bottom:10px" >
                            <p:selectOneRadio layout="pageDirection" columns="1"  value="#{ManageModelsManagedBean.tagTypeOfInsertion}">
                                <f:selectItem itemLabel="Adicionar Classificação" itemValue="newClassification"  />
                                <f:selectItem itemLabel="Remover Classificação" itemValue="removeClassification"  />
                                <f:selectItem itemLabel="Editar Classificação" itemValue="editClassification"  />
                                <p:ajax update="@form" />
                            </p:selectOneRadio>
                        </h:panelGrid>

                        <p:separator/>
                        <fn:choose >

                            <fn:when test="#{ManageModelsManagedBean.newClassificationSelected}">

                                <h:panelGrid columns="1">
                                    <h:outputText style="font-weight: bold" value="Adicionar Classificação"/>
                                    <br/>
                                    <h:outputText value="Selecione uma classificação no menu acima para adicionar uma subclassificação"/>

                                    <fn:if test="${empty ManageModelsManagedBean.selectedTag.title}">
                                        <h:outputText class="tituloInfo" value="Nenhuma tag selecionada"/>
                                    </fn:if>
                                    <fn:if test="${not empty ManageModelsManagedBean.selectedTag.title}">
                                        <p:commandLink update="@form" class="tituloInfo" value="Tag selecionada: #{ManageModelsManagedBean.selectedTag}" action="#{ManageModelsManagedBean.unselectTag}"/>
                                    </fn:if>

                                    <p:inputText class="centralizar" value="#{ManageModelsManagedBean.actualTag.title}"/>
                                    <p:commandButton  style="margin-top: 10px" class="centralizar" value="Adicionar Classificação" update="@form" action="#{ManageModelsManagedBean.finishAddTag()}"/>
                                </h:panelGrid>
                            </fn:when>  

                            <fn:when test="#{ManageModelsManagedBean.removeClassificationSelected}">

                                <h:panelGrid columns="1">
                                    <h:outputText style="font-weight: bold" value="Remover classificação"/>
                                    <br/>
                                    <h:outputText value="Selecione uma classificação e clique em remover classificação"/>

                                    <fn:if test="${empty ManageModelsManagedBean.selectedTag.title}">
                                        <h:outputText class="tituloInfo" value="Nenhuma tag selecionada"/>
                                    </fn:if>
                                    <fn:if test="${not empty ManageModelsManagedBean.selectedPart.title}">
                                        <p:commandLink update="@form" class="tituloInfo" value="Tag selecionada: #{ManageModelsManagedBean.selectedTag}" action="#{ManageModelsManagedBean.unselectTag}"/>
                                    </fn:if>
                                    <p:commandButton style="margin-top: 10px" class="centralizar" value="Remover classificação" update="@form" action="#{ManageModelsManagedBean.removeTag()}"/>
                                </h:panelGrid>
                            </fn:when>  


                            <fn:when test="#{ManageModelsManagedBean.editClassificationSelected}">

                                <h:panelGrid columns="1">
                                    <h:outputText style="font-weight: bold" value="Editar Classificação"/>
                                    <br/>
                                    <h:outputText value="Selecione uma classificação no menu acima, digite o novo nome para a classificação e salve as alterações"/>

                                    <p:inputText class="centralizar" style="margin-top: 10px" disabled="true" value="#{ManageModelsManagedBean.selectedTag.title}"/>
                                    <p:inputText class="centralizar" style="margin-top: 10px"  value="#{ManageModelsManagedBean.actualTag.title}"/>
                                    <p:commandButton  style="margin-top: 10px" class="centralizar" value="Salvar Alterações" update="@form" action="#{ManageModelsManagedBean.finishAddTag()}"/>
                                </h:panelGrid>
                            </fn:when> 
                        </fn:choose>
                    </div>
                </h:form>
            </div>
        </div>
        <fn:choose>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.defaultFooter}">
                <ui:include src="/Public/Components/Footers/DefaultFooter.xhtml"/>
            </fn:when>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.slimFooter}">
                <ui:include src="/Public/Components/Footers/SlimFooter.xhtml"/>
            </fn:when>
        </fn:choose>
    </h:body>
</html>