Aplicações/Sistema juridico/Code/src/java/View/ManageClientManagedBean.java
package View;

import Controler.ClientJpaController;
import Controler.CompanyJpaController;
import Controler.AdminJpaController;
import Utilitarios.EmProvider;
import Controler.exceptions.NonexistentEntityException;
import Model.Client;
import Model.Company;
import Model.Admin;
import Utilitarios.GetCEP;
import static java.awt.SystemColor.control;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import javax.persistence.Query;

@ManagedBean
@RequestScoped
public class ManageClientManagedBean {

    public ManageClientManagedBean() {
    }

    private Client actualClient = new Client();
    private Company actualCompany = new Company();
    private List<Client> listClients = new ArrayList<>();
    private List<Company> listCompany = new ArrayList<>();

    private ClientJpaController controlClient = new ClientJpaController(EmProvider.getInstance().getEntityManagerFactory());
    private CompanyJpaController controlCompany = new CompanyJpaController(EmProvider.getInstance().getEntityManagerFactory());
    private AdminJpaController controlUser = new AdminJpaController(EmProvider.getInstance().getEntityManagerFactory());

    private String filter;
    private String filterCompany;
    private String typeOfPerson;

    //goto
    public String goToAddClients() {
        return "/Public/ClientModule/AddClient?faces-redirect=true";
    }

    public String goToEditClient() {
        typeOfPerson = "newPF";
        return "/Public/ClientModule/EditClient?faces-redirect=true";
    }
    
    public String goToEditCompany() {
        typeOfPerson = "newPJ";
        return "/Public/ClientModule/EditClient?faces-redirect=true";
    }

    public String goToManageClients() {
        getAllClients();
        getAllCompanys();
        return "/Public/ClientModule/ManageClients?faces-redirect=true";
    }

    public boolean isPfSelected() {
        if ("newPF".equals(typeOfPerson)) {
            return true;
        }
        return false;
    }

    public boolean isPjSelected() {
        if ("newPJ".equals(typeOfPerson)) {
            return true;
        }
        return false;
    }

    public void findCep() {
        String cep = actualClient.getCep();

        GetCEP c = new GetCEP();
        try {
            actualClient.setCity(c.getCidade(cep));
            actualClient.setState(c.getUF(cep));
            actualClient.setAddress1(c.getEndereco(cep));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void findCepCompany() {
        String cep = actualCompany.getCep();

        GetCEP c = new GetCEP();
        try {
            actualCompany.setCity(c.getCidade(cep));
            actualCompany.setState(c.getUF(cep));
            actualCompany.setAddress1(c.getEndereco(cep));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //Find
    public void filterClientsByName() {
        listClients.clear();

        List<Client> result = new ArrayList<>();

        EntityManager em = EmProvider.getInstance().getEntityManagerFactory().createEntityManager();
        Query q = em.createQuery("SELECT t FROM Client t WHERE t.fullName LIKE :fullName", Client.class
        );
        q.setParameter("fullName", "%" + filter + "%");
        result = q.getResultList();
        listClients = result;
    }

    public void filterCompanyByName() {
        listCompany.clear();

        List<Company> result = new ArrayList<>();

        EntityManager em = EmProvider.getInstance().getEntityManagerFactory().createEntityManager();
        Query q = em.createQuery("SELECT t FROM Company t WHERE t.name LIKE :name", Company.class);
        q.setParameter("name", "%" + filterCompany + "%");
        result = q.getResultList();
        listCompany = result;
    }

    public List<Client> getAllClients() {
        listClients.clear();
        EntityManager em = EmProvider.getInstance().getEntityManagerFactory().createEntityManager();
        listClients = controlClient.findClientEntities();
        return listClients;
    }
    
    public List<Company> getAllCompanys() {
        listCompany.clear();
        EntityManager em = EmProvider.getInstance().getEntityManagerFactory().createEntityManager();
        listCompany = controlCompany.findCompanyEntities();
        return listCompany;
    }

    public void carregarUsuarios() {
        getAllClients();
    }

    public void clear() {
        actualClient = new Client();
    }

    public String finishAddClient() {
        try {
            Admin actualUser = controlUser.findAdmin(ManageSession.getUserName());
            actualClient.setAdminloginUser(actualUser);
            controlClient.create(actualClient);
            actualClient = new Client();
            getAllClients();
            return "/Public/ClientModule/ManageClients";
        } catch (Exception ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "/Public/ErrorPages/ErrorIncluding";
    }

    // edit
    public String finishEditClient() {
        try {
            controlClient.edit(actualClient);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha :("));
        } catch (Exception ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha!"));
        }
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Sucesso!"));
        actualClient = controlClient.findClient(actualClient.getCpfRegister());
        return "/Public/ClientModule/ManageClients";

    }

    //Excluir
    public String removeClient() {
        try {
            controlClient.destroy(actualClient.getCpfRegister());
            actualClient = new Client();
            getAllClients();
            return "/Public/ClientModule/ManageClients";
        } catch (Exception e) {
            e.printStackTrace();
            return "/Public/ErrorPages/ErrorDeleting";
        }

    }

    public String finishAddCompany() {
        try {
            Admin actualUser = controlUser.findAdmin(ManageSession.getUserName());
            actualCompany.setAdminloginUser(actualUser);
            controlCompany.create(actualCompany);
            actualCompany = new Company();
            getAllClients();
            return "/Public/ClientModule/ManageClients";
        } catch (Exception ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "/Public/ErrorPages/ErrorIncluding";
    }

    // edit
    public String finishEditCompany() {
        try {
            controlCompany.edit(actualCompany);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha :("));
        } catch (Exception ex) {
            Logger.getLogger(ManageClientManagedBean.class.getName()).log(Level.SEVERE, null, ex);
            FacesContext context = FacesContext.getCurrentInstance();
            context.addMessage(null, new FacesMessage("Falha!"));
        }
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage("Sucesso!"));
        actualCompany = controlCompany.findCompany(actualCompany.getCnpj());
        return "/Public/ClientModule/ManageClients";

    }

    //Excluir
    public String removeCompany() {
        try {
            controlCompany.destroy(actualCompany.getCnpj());
            actualCompany = new Company();
            getAllClients();
            return "/Public/ClientModule/ManageClients";
        } catch (Exception e) {
            e.printStackTrace();
            return "/Public/ErrorPages/ErrorDeleting";
        }

    }

    public Client getActualClient() {
        return actualClient;
    }

    public void setActualClient(Client actualClient) {
        this.actualClient = actualClient;
    }

    public List<Client> getListClients() {
        return listClients;
    }

    public void setListClients(List<Client> listClients) {
        this.listClients = listClients;
    }

    public ClientJpaController getControlClient() {
        return controlClient;
    }

    public void setControlClient(ClientJpaController controlClient) {
        this.controlClient = controlClient;
    }

    public String getFilter() {
        return filter;
    }

    public void setFilter(String filter) {
        this.filter = filter;
    }

    public String getTypeOfPerson() {
        return typeOfPerson;
    }

    public void setTypeOfPerson(String typeOfPerson) {
        this.typeOfPerson = typeOfPerson;
    }

    public Company getActualCompany() {
        return actualCompany;
    }

    public void setActualCompany(Company actualCompany) {
        this.actualCompany = actualCompany;
    }

    public String getFilterCompany() {
        return filterCompany;
    }

    public void setFilterCompany(String filterCompany) {
        this.filterCompany = filterCompany;
    }

    public List<Company> getListCompany() {
        return listCompany;
    }

    public void setListCompany(List<Company> listCompany) {
        this.listCompany = listCompany;
    }
}

Aplicações/Sistema juridico/Code/src/java/View/ManageLoginManagedBean.java
package View;


import Utilitarios.EmProvider;
import Controler.exceptions.IllegalOrphanException;
import Controler.exceptions.NonexistentEntityException;
import Components.ComponentsContainer;
import Controler.AdminJpaController;
import Model.Admin;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;


public class ManageLoginManagedBean {
    
    
    public ManageLoginManagedBean() {
    }
    
    private Admin actualAdmin = new Admin();
    private List<Admin> administrator = new ArrayList<>();
    private AdminJpaController control = new AdminJpaController(EmProvider.getInstance().getEntityManagerFactory());
    
    
    public String gotoLogin(){
        return "/Admin/login";
    }
     
      
      
    public String finishEditarAdministrador() throws NonexistentEntityException, Exception, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException, NonexistentEntityException{
        control.edit(actualAdmin);
        actualAdmin = new Admin();
        return "gotoGerenciarAdministrador";
    }
   
     
    public String gotoGerenciarAdministrador(){ 
        //SecretariaJpaController control = new SecretariaJpaController(EmProvider.getInstance().getEntityManagerFactory());
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String gotoAdicionarAdministrador(){
        return "gotoAdicionarAdministrador";
    }
    
    public String finishAdicionarAdministrador() throws Exception{
        control.create(actualAdmin);
        actualAdmin = new Admin();
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String excluirAdministrador() throws IllegalOrphanException, NonexistentEntityException{
        //PrefeitoJpaController control = new PrefeitoJpaController(EmProvider.getInstance().getEntityManagerFactory());
        control.destroy(actualAdmin.getLoginUser());
        actualAdmin = new Admin();
        administrator = control.findAdminEntities();
        return "gotoGerenciarAdministrador";
    }
    
    public String gotoAdicionarArquivoAdministrador(){
        actualAdmin = control.findAdmin(actualAdmin.getLoginUser());
        return "gotoAdicionarArquivoAdministrador";
    }
    
    public String gotoVisualizarImagem(){
        return "gotoVisualizarImagem";
    }
    
    public String finalizarAdicaoFotosAdministrador(){
        return "gotoGerenciarAdministrador";
    }
    
    public String validateUsernamePassword() {
        
        
        if (validateUser(actualAdmin)) {
            HttpSession session = ManageSession.getSession();
            session.setAttribute("username", actualAdmin.getLoginUser());
            return "Welcome";
        } else {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage(FacesMessage.SEVERITY_WARN,
                            "Senha Incorreta",
                            "Por favor, tente novamente"));
            return "login";
        }
    }
    
    public boolean validateUser(Admin comparar){
        Admin validate = control.findAdmin(actualAdmin.getLoginUser());
        if (validate == null){
            return false;
        }
        if(validate.getLoginUser().equals(comparar.getLoginUser()) && 
                validate.getPasswordUser().equals(comparar.getPasswordUser())){
            return true;
        }
        return false;
    }
 
    //logout event, invalidate session
    public String logout() {
        HttpSession session = ManageSession.getSession();
        session.invalidate();
        return "/Public/Dashboard";
    }
    
    public ComponentsContainer getComponentsContainer(){
        return new ComponentsContainer();
    }
    
    public Admin getActualAdmin() {
        return actualAdmin;
    }

    public void setActualAdmin(Admin actualAdmin) {
        this.actualAdmin = actualAdmin;
    }

    public List<Admin> getAdmin() {
        return administrator;
    }

    public void setAdmin(List<Admin> administrator) {
        this.administrator = administrator;
    }

    public AdminJpaController getControl() {
        return control;
    }

    public void setControl(AdminJpaController control) {
        this.control = control;
    }

    
    
    
    
}

Aplicações/Sistema juridico/Code/web/Public/ClientModule/ManageClients.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p ="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:fn="http://java.sun.com/jsp/jstl/core">

    <ui:include src="/Public/Includes/HeadIncludesPublic.xhtml"/>


    <h:body>

        <div class="content">
            <ui:include src="/Public/Components/Headers/Header.xhtml"/>

            <fn:choose>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.primeNav}">
                    <ui:include src="/Public/Components/Navs/PrimeNav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.defaultNav}">
                    <ui:include src="/Public/Components/Navs/Nav.xhtml"/>
                </fn:when>
                <fn:when test="#{ManageLoginManagedBean.componentsContainer.nav.bootstrapNav}">
                    <ui:include src="/Public/Components/Navs/BootstrapNav.xhtml"/>
                </fn:when>

            </fn:choose>
            <nav class="positionSideLinks tree">
                <p:commandButton class="colorLink" action="#{ManageClientManagedBean.goToAddClients}" value="Adicionar Cliente"/>

            </nav>

            <div class="page-content">

                <div class="tituloTopico">jusHelp - Gerenciar Clientes</div>

                <div class="textoExtenso">
                    A seguinte lista contém todos os clientes cadastrados em seu sistema <br/><br/>

                    Utilize as "ações" para remover, editar e visualizar o cadastro de seus clientes</div>




                <p:growl autoUpdate="true"/>

                <h:form style="float:left; width: 90%; margin: 3%">

                    <div class="formElements">
                        <div style="margin-bottom: 2%">Selecione um tipo de pessoa para adicionar</div>
                        <h:selectOneMenu styleClass="form-control"  value="#{ManageClientManagedBean.typeOfPerson}">
                            <f:selectItem itemLabel="Pessoa física" itemValue="newPF"  />
                            <f:selectItem itemLabel="Pessoa Jurídica" itemValue="newPJ"  />
                            <p:ajax update="@form" />
                        </h:selectOneMenu>
                    </div>
                    
                    <fn:choose >

                        <fn:when test="#{ManageClientManagedBean.pfSelected}">

                            <div class="formElements">

                                <div class="formElements" style="margin-left: 0; float: left;">
                                    <div>Digite abaixo o nome do cliente</div>
                                    <p:inputText class="centralizar" value="#{ManageClientManagedBean.filter}" placeholder="Digite aqui" >
                                        <p:ajax event="keyup" listener="#{ManageClientManagedBean.filterClientsByName}" update="tableClients"/>
                                    </p:inputText>
                                </div>

                                <div class="tablePannel" style="float:left;">
                                    <p:dataTable id="tableClients" var="cli"  paginator="true" rows="30" value="#{ManageClientManagedBean.listClients}">

                                        <p:column headerText="Nome completo">
                                            <h:outputText value="#{cli.fullName}" />
                                        </p:column>

                                        <p:column headerText="E-mail">
                                            <h:outputText value="#{cli.email}" />
                                        </p:column>

                                        <p:column headerText="CPF">
                                            <h:outputText value="#{cli.cpfRegister}" />
                                        </p:column>


                                        <p:column style="width: 23%" headerText="Actions">

                                            <p:commandButton icon="ui-icon-close" action="#{ManageClientManagedBean.removeClient}" update="tableClients" >
                                                <f:setPropertyActionListener target="#{ManageClientManagedBean.actualClient}" value="#{cli}"/>
                                                <p:confirm header="Confirmação" message="Tem certeza que deseja remover o cliente?" icon="ui-icon-alert" />
                                            </p:commandButton>

                                            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                                                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                                            </p:confirmDialog>

                                            <p:commandButton icon="ui-icon-pencil" action="#{ManageClientManagedBean.goToEditClient}">
                                                <f:setPropertyActionListener target="#{ManageClientManagedBean.actualClient}" value="#{cli}"/>
                                            </p:commandButton>

                                        </p:column>
                                    </p:dataTable>
                                </div>  
                            </div>
                        </fn:when>

                        <fn:when test="#{ManageClientManagedBean.pjSelected}">
                            <div class="formElements">

                                <div class="formElements" style="margin-left: 0; float: left;">
                                    <div>Digite abaixo o nome do empresa</div>
                                    <p:inputText class="centralizar" value="#{ManageClientManagedBean.filterCompany}" placeholder="Digite aqui" >
                                        <p:ajax event="keyup" listener="#{ManageClientManagedBean.filterCompanyByName}" update="tableCompany"/>
                                    </p:inputText>
                                </div>

                                <div class="tablePannel" style="float:left;">
                                    <p:dataTable id="tableCompany" var="cli"  paginator="true" rows="30" value="#{ManageClientManagedBean.listCompany}">

                                        <p:column headerText="CNPJ">
                                            <h:outputText value="#{cli.cnpj}" />
                                        </p:column>

                                        <p:column headerText="Nome/Razão social">
                                            <h:outputText value="#{cli.name}" />
                                        </p:column>

                                        <p:column headerText="e-mail">
                                            <h:outputText value="#{cli.email}" />
                                        </p:column>


                                        <p:column style="width: 23%" headerText="Actions">

                                            <p:commandButton icon="ui-icon-close" action="#{ManageClientManagedBean.removeCompany()}" update="tableCompany" >
                                                <f:setPropertyActionListener target="#{ManageClientManagedBean.actualCompany}" value="#{cli}"/>
                                                <p:confirm header="Confirmação" message="Tem certeza que deseja remover o cliente?" icon="ui-icon-alert" />
                                            </p:commandButton>

                                            <p:confirmDialog global="true" showEffect="fade" hideEffect="fade">
                                                <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
                                                <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
                                            </p:confirmDialog>

                                            <p:commandButton icon="ui-icon-pencil" action="#{ManageClientManagedBean.goToEditCompany()}">
                                                <f:setPropertyActionListener target="#{ManageClientManagedBean.actualCompany}" value="#{cli}"/>
                                            </p:commandButton>

                                        </p:column>
                                    </p:dataTable>
                                </div>  
                            </div>
                        </fn:when>
                    </fn:choose>
                </h:form>

            </div>

        </div>
        <fn:choose>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.defaultFooter}">
                <ui:include src="/Public/Components/Footers/DefaultFooter.xhtml"/>
            </fn:when>
            <fn:when test="#{ManageLoginManagedBean.componentsContainer.footers.slimFooter}">
                <ui:include src="/Public/Components/Footers/SlimFooter.xhtml"/>
            </fn:when>
        </fn:choose>
    </h:body>
</html>